include: 'package:effective_dart/analysis_options.yaml'

analyzer:
  exclude:
    - lib/**/*.g.dart
    - lib/**/*.chopper.dart

linter:
  rules:
    avoid_classes_with_only_static_members: false
    annotate_overrides: true
    await_only_futures: true
    public_member_api_docs: false
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    avoid_positional_boolean_parameters: false
    avoid_catches_without_on_clauses: false