name: flutter_taskly
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  package_info: ^2.0.0
  flutter_svg: ^0.20.0-nullsafety.3
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  chopper: ^3.0.6
  provider: ^5.0.0
  get_it: ^6.0.0
  animations: ^2.0.0
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  effective_dart: ^1.3.1
  chopper_generator: ^3.0.6
  build_runner: ^1.11.1
  mobx_codegen: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/vectors/